=== paparazzi/pprzlink/message_definitions/v1.0/messages.dtd
<!ELEMENT protocol (msg_class+)>
<!ATTLIST protocol>

<!ELEMENT msg_class (message+)>
<!ATTLIST msg_class
  name CDATA #REQUIRED
  id   CDATA #IMPLIED
>

<!ELEMENT message (description?,field*)>
<!ATTLIST message
  name CDATA #REQUIRED
  id   CDATA #REQUIRED
  link CDATA #IMPLIED
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  format CDATA #IMPLIED
  unit CDATA #IMPLIED
  values CDATA #IMPLIED
  alt_unit CDATA #IMPLIED
  alt_unit_coef CDATA #IMPLIED
>

=== paparazzi/pprzlink/message_definitions/v1.0/messages.xml
<?xml version="1.0"?>
<!DOCTYPE protocol SYSTEM "messages.dtd">
<protocol>
 <!-- messages from modem or sim to server -->
 <msg_class name="telemetry" id="1">

    <message name="AUTOPILOT_VERSION" id="1">
      <field name="version" type="uint32">version encoded as: MAJOR * 10000 + MINOR * 100 + PATCH</field>
      <field name="desc" type="char[]">version description as string from paparazzi_version</field>
    </message>

    <message name="ALIVE" id="2">
     <description>alive/heartbeat message containing the MD5sum of the aircraft configuration</description>
      <field name="md5sum" type="uint8[]"/>
    </message>

    <message name="PONG" id="3">
     <description>Answer to PING datalink message, to measure latencies</description>
    </message>

    <message name="TAKEOFF" id="4">
      <field name="cpu_time" type="uint16" unit="s"></field>
    </message>

    <message name="ARDRONE_NAVDATA" id="5">
      <field name="taille" type="uint16" />
      <field name="nu_trame" type="uint16" />
      <field name="ax" type="uint16" />
      <field name="ay" type="uint16" />
      <field name="az" type="uint16" />
      <field name="vx" type="int16" />
      <field name="vy" type="int16" />
      <field name="vz" type="int16" />
      <field name="temperature_acc" type="uint16" />
      <field name="temperature_gyro" type="uint16" />
      <field name="ultrasound" type="uint16" />
      <field name="us_debut_echo" type="uint16" />
      <field name="us_fin_echo" type="uint16" />
      <field name="us_association_echo" type="uint16" />
      <field name="us_distance_echo" type="uint16" />
      <field name="us_curve_time" type="uint16" />
      <field name="us_curve_value" type="uint16" />
      <field name="us_curve_ref" type="uint16" />
      <field name="nb_echo" type="uint16" />
      <field name="sum_echo" type="uint32" />
      <field name="gradient" type="int16" />
      <field name="flag_echo_ini" type="uint16" />
      <field name="pressure" type="int32" />
      <field name="temperature_pressure" type="uint16" />
      <field name="mx" type="int16" />
      <field name="my" type="int16" />
      <field name="mz" type="int16" />
      <field name="chksum" type="uint16" />
      <field name="checksum_errors" type="uint32" />
    </message>

    <message name="ATTITUDE" id="6">
      <field name="phi"   type="float" unit="rad" alt_unit="deg"/>
      <field name="psi"   type="float" unit="rad" alt_unit="deg"/>
      <field name="theta" type="float" unit="rad" alt_unit="deg"/>
    </message>

    <!-- 7 is free-->

    <message name="GPS" id="8">
      <field name="mode"       type="uint8"  unit="byte_mask"/>
      <field name="utm_east"   type="int32"  unit="cm" alt_unit="m"/>
      <field name="utm_north"  type="int32"  unit="cm" alt_unit="m"/>
      <field name="course"     type="int16"  unit="decideg" alt_unit="deg"/>
      <field name="alt"        type="int32"  unit="mm" alt_unit="m">Altitude above geoid (MSL)</field>
      <field name="speed"      type="uint16" unit="cm/s" alt_unit="m/s">norm of 2d ground speed in cm/s</field>
      <field name="climb"      type="int16"  unit="cm/s" alt_unit="m/s"/>
      <field name="week"       type="uint16" unit="weeks"/>
      <field name="itow"       type="uint32" unit="ms"/>
      <field name="utm_zone"   type="uint8"/>
      <field name="gps_nb_err" type="uint8"/>
    </message>

    <message name="NAVIGATION_REF" id="9">
      <field name="utm_east"  type="int32" unit="m"/>
      <field name="utm_north" type="int32" unit="m"/>
      <field name="utm_zone" type="uint8"/>
      <field name="ground_alt" type="float" unit="m"/>
    </message>

    <message name="NAVIGATION" id="10">
      <field name="cur_block" type="uint8"/>
      <field name="cur_stage" type="uint8"/>
      <field name="pos_x" type="float" unit="m" format="%.1f"/>
      <field name="pos_y" type="float" unit="m" format="%.1f"/>
      <field name="dist_wp" type="float" format="%.1f" unit="m"/>
      <field name="dist_home" type="float" format="%.1f" unit="m"/>
      <field name="flight_time" type="uint16" unit="s"/>
      <field name="block_time" type="uint16" unit="s"/>
      <field name="stage_time" type="uint16" unit="s"/>
      <field name="kill_auto_throttle" type="uint8" unit="bool"/>
      <field name="circle_count" type="uint8"/>
      <field name="oval_count" type="uint8"/>
    </message>

    <message name="PPRZ_MODE" id="11">
      <field name="ap_mode" type="uint8" values="MANUAL|AUTO1|AUTO2|HOME|NOGPS|FAILSAFE"/>
      <field name="ap_gaz" type="uint8" values="MANUAL|AUTO_THROTTLE|AUTO_CLIMB|AUTO_ALT"/>
      <field name="ap_lateral" type="uint8" values="MANUAL|ROLL_RATE|ROLL|COURSE"/>
      <field name="ap_horizontal" type="uint8" values="WAYPOINT|ROUTE|CIRCLE"/>
      <field name="if_calib_mode" type="uint8" values="NONE|DOWN|UP"/>
      <field name="mcu1_status" type="uint8" values="LOST|OK|REALLY_LOST"/>
    </message>

    <message name="ENERGY" id="12">
      <field name="throttle"  type="uint8" unit="%">Throttle setting</field>
      <field name="voltage"   type="float" unit="V">Input battery voltage</field>
      <field name="current"   type="float" unit="A">Current consumption</field>
      <field name="power"     type="float" unit="W">Electrical power</field>
      <field name="avg_power" type="float" unit="W">Average electrical power</field>
      <field name="charge"    type="float" unit="Ah">Accumulated consumed charge</field>
      <field name="energy"    type="float" unit="Wh">Accumulated consumed energy</field>
    </message>

    <!-- 13 is free-->

    <message name="CALIBRATION" id="14">
      <field name="climb_sum_err" type="float" format="%.1f"/>
      <field name="climb_gaz_submode" type="uint8"/>
    </message>

    <message name="SETTINGS" id="15">
      <field name="slider_1_val" type="float"/>
      <field name="slider_2_val" type="float"/>
    </message>

    <message name="DESIRED" id="16">
      <field name="roll" type="float" format="%.2f" unit="rad" alt_unit="deg" alt_unit_coef="57.3"/>
      <field name="pitch" type="float" format="%.2f" unit="rad" alt_unit="deg" alt_unit_coef="57.3"/>
      <field name="course" type="float" format="%.1f" unit="rad" alt_unit="deg" alt_unit_coef="57.3"/>
      <field name="x" type="float" format="%.0f"  unit="m"/>
      <field name="y" type="float" format="%.0f" unit="m"/>
      <field name="altitude" type="float" format="%.0f"  unit="m"/>
      <field name="climb" type="float" format="%.1f"  unit="m/s"></field>
      <field name="airspeed" type="float" format="%.1f"  unit="m/s"></field>
    </message>

    <message name="GPS_SOL" id="17">
      <field name="Pacc" type="uint32" unit="cm"/>
      <field name="Sacc" type="uint32" unit="cm/s"/>
      <field name="PDOP" type="uint16"/>
      <field name="numSV" type="uint8"/>
    </message>

    <message name="ADC_GENERIC" id="18">
      <field name="val1" type="uint16"/>
      <field name="val2" type="uint16"/>
    </message>

    <!-- 19 is free-->

    <message name="CAM" id="20">
      <field name="pan" type="int16" unit="deg"/>
      <field name="tilt" type="int16" unit="deg"/>
      <field name="target_x" type="int16" unit="m"/>
      <field name="target_y" type="int16" unit="m"/>
    </message>

    <message name="CIRCLE" id="21">
      <field name="center_east" type="float" unit="m"/>
      <field name="center_north" type="float" unit="m"/>
      <field name="radius" type="float" unit="m"/>
    </message>

    <message name="SEGMENT" id="22">
      <field name="segment_east_1" type="float" unit="m"/>
      <field name="segment_north_1" type="float" unit="m"/>
      <field name="segment_east_2" type="float" unit="m"/>
      <field name="segment_north_2" type="float" unit="m"/>
    </message>

    <message name="VECTORNAV_INFO" id="23">
      <field name="timestamp"     type="float"    unit="s"/>
      <field name="chksm_error"   type="uint32"/>
      <field name="hdr_error"     type="uint32"/>
      <field name="rate" type="uint16" unit="packets/s"/>
      <field name="ins_status" type="uint8" values="NoTracking|OutOfSpecs|OK"/>
      <field name="ins_err" type="uint8"/>
      <field name="YprU1"     type="float"    unit="deg"/>
      <field name="YprU2"     type="float"    unit="deg"/>
      <field name="YprU3"     type="float"    unit="deg"/>
    </message>

    <message name="HYBRID_GUIDANCE" id="24">
      <field name="pos_x" type="int32" alt_unit="m" alt_unit_coef="0.0039063"/>
      <field name="pos_y" type="int32" alt_unit="m" alt_unit_coef="0.0039063"/>
      <field name="speed_x" type="int32" alt_unit="m/s" alt_unit_coef="0.0000019"/>
      <field name="speed_y" type="int32" alt_unit="m/s" alt_unit_coef="0.0000019"/>
      <field name="wind_x" type="int32" alt_unit="m/s" alt_unit_coef="0.0039063"/>
      <field name="wind_y" type="int32" alt_unit="m/s" alt_unit_coef="0.0039063"/>
      <field name="pos_err_x" type="int32" alt_unit="m" alt_unit_coef="0.0039063"/>
      <field name="pos_err_y" type="int32" alt_unit="m" alt_unit_coef="0.0039063"/>
      <field name="speed_sp_x" type="int32" alt_unit="m/s" alt_unit_coef="0.0039063"/>
      <field name="speed_sp_y" type="int32" alt_unit="m/s" alt_unit_coef="0.0039063"/>
      <field name="norm_ref_speed" type="int32" alt_unit="m/s" alt_unit_coef="0.0039063"/>
      <field name="heading_diff" type="int32"/>
      <field name="phi" type="int32" alt_unit="deg" alt_unit_coef="0.0139882"/>
      <field name="theta" type="int32" alt_unit="deg" alt_unit_coef="0.0139882"/>
      <field name="psi" type="int32" alt_unit="deg" alt_unit_coef="0.0139882"/>
    </message>

    <message name="SVINFO" id="25">
      <field name="chn" type="uint8"/>
      <field name="SVID" type="uint8"/>
      <field name="Flags" type="uint8"/>
      <field name="QI" type="uint8"/>
      <field name="CNO" type="uint8" unit="dbHz"/>
      <field name="Elev" type="int8" unit="deg"/>
      <field name="Azim" type="int16" unit="deg"/>
